### ISSUE TITLE
'LineProfilerMiddleware' object has no attribute 'route' : Issue with Flask

### ISSUE THREAD

**Issue by rohithpr** [ymyzk/wsgi_lineprof#36]
I have a simple Flask app:

```
from flask import Flask
from wsgi_lineprof.middleware import LineProfilerMiddleware

app = Flask('zapp')
app = LineProfilerMiddleware(app)

@app.route('/')
def index():
    return 'Hello'

if __name__ == '__main__':
    app.run(port=8000)
```

Running it gives the following error message:

```
» python app.py
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    @app.route('/')
AttributeError: 'LineProfilerMiddleware' object has no attribute 'route'
```

---

I tried changing `app = LineProfilerMiddleware(app)` to `app = LineProfilerMiddleware(app).app`. This lets me run the app but I no longer get any profiling results.

---

Other info:

Flask==1.1.1
wsgi-lineprof==0.8.0
Python 3.7.4

**Comment by ymyzk** [comment]
Hi, thanks for asking a question. When we're using Flask, we need to wrap `app.wsgi_app` with the middleware instead of `app`. Ref: https://flask.palletsprojects.com/en/1.1.x/api/?highlight=wsgi_app#flask.Flask.wsgi_app

Could you try the following? I'd like to also explain this in our document.
```python
from flask import Flask
from wsgi_lineprof.middleware import LineProfilerMiddleware

app = Flask('zapp')
app.wsgi_app = LineProfilerMiddleware(app.wsgi_app)

@app.route('/')
def index():
    return 'Hello'

if __name__ == '__main__':
    app.run(port=8000)
```

**Comment by ymyzk** [comment]
The latest document now includes an example usage with Flask: https://wsgi-lineprof.readthedocs.io/en/latest/examples.html#flask

**Comment by ymyzk** [comment]
I'd like to add an example for Django as well. Please wait for a bit more 🙂

**Comment by ymyzk** [comment]
An example with Django was added in #39
